# å·¥ä½œæµåç§°
name: Generate

# å·¥ä½œæµè§¦å‘æ—¶æœº, see: https://docs.github.com/zh/actions/using-workflows/triggering-a-workflow
# è§¦å‘æ¡ä»¶ä¿®æ”¹ä¸º: å½“ main åˆ†æ”¯æœ‰ push æ“ä½œ || æ¯å¤© 0 ç‚¹
on:
  schedule:
    - cron: '30 22 * * *'
  push:
    branches: 
      - main  

# ä½œä¸š, see: https://docs.github.com/zh/actions/using-jobs/using-jobs-in-a-workflow
jobs:
  # ä½¿ç”¨ actions/checkout, see: https://github.com/actions/checkout
  checkout:
    - name: Checkout
      uses: actions/checkout@v3

  # æ’å…¥æ˜é‡‘åˆ—è¡¨, ä½¿ç”¨ KunLunXu-CC/juejin-posts-action ç”Ÿæˆæ–‡ç« åˆ—è¡¨, see: https://github.com/KunLunXu-CC/juejin-posts-action
  juejin-posts: 
    nodes: [checkout]
    steps:
      - name: Append Juejin Posts ListğŸ”§
        uses: KunLunXu-CC/juejin-posts-action@main
        with: 
          user_id: "4459274891717223"
  
  # æˆç»Ÿè®¡å›¾, see: https://github.com/lowlighter/metrics
  github-metrics: 
    nodes: [checkout]
    steps:
      - name: metrics-Half-year-calendar
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: assets/metrics.plugin.isocalendar.svg
          token: ${{ github.token }}
          plugin_isocalendar: yes
  
  # åˆ›å»º Snake, ç”¨ Platane/snk ç”Ÿæˆå›¾ç‰‡, see: https://github.com/Platane/snk
  github-Snake: 
    nodes: [checkout]
    steps:
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
            assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

  # step 2. ä½¿ç”¨ EndBug/add-and-commit æäº¤ä»£ç , see: https://github.com/EndBug/add-and-commit
  push:
    nodes: [juejin-posts, github-metrics, github-Snake]
    steps:
      - run: |
          git pull
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          default_author: github_actions
          message: 'juejin-posts'